# Generated by Django 4.1.2 on 2022-11-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_auction_comment_bid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction",
            name="end_date",
        ),
        migrations.AddField(
            model_name="auction",
            name="duration",
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name="auction",
            name="start_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
